name: Build Wheels

on:
  pull_request:
    banches:
      - main
  push:
    tags:
    - '*'

env:
  PYTHON_VERSION: '3.11.9'
  CIBW_VERSION: '2.21.3'
  CIBW_BUILD: 'cp311-*'
  CIBW_SKIP: '*-musllinux_*'
  CIBW_BUILD_VERBOSITY: 1
  CIBW_BUILD_FRONTEND: 'build[uv]'
  SQLITE_VERSION: '3.46.1'

jobs:
  build_sqlite_amalgamation:
    name: Build SQLite Amalgamation
    runs-on: ubuntu-latest

    steps:
      - name: Clone SQLite repository
        run: |
          git clone https://github.com/sqlite/sqlite.git sqlite-src
          cd sqlite-src
          git checkout version-${{ env.SQLITE_VERSION }}

      - name: Build SQLite amalgamation
        run: |
          cd sqlite-src
          mkdir build
          cd build
          ../configure
          make sqlite3.c

      - name: Upload SQLite amalgamation files
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-amalgamation
          path: |
            sqlite-src/build/sqlite3.c
            sqlite-src/build/sqlite3.h
          retention-days: 1

  build_wheels_macos:
    name: Build macOS wheels (${{ matrix.arch }})
    runs-on: macos-13
    needs: build_sqlite_amalgamation
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Download SQLite amalgamation
        uses: actions/download-artifact@v4
        with:
          name: sqlite-amalgamation
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install cibuildwheel
        run: |
          pip install cibuildwheel[uv]==${{ env.CIBW_VERSION }}

      - name: Build wheels
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        run: |
          python -m cibuildwheel --output-dir dist

      - name: Upload macOS wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-macos-${{ matrix.arch }}-cp311
          path: dist/*.whl

  build_wheels_linux:
    name: Build Linux wheels (${{ matrix.arch.name }})
    runs-on: ${{ matrix.arch.runner }}
    needs: build_sqlite_amalgamation
    strategy:
      matrix:
        arch:
          - name: aarch64
            runner: ubuntu-24.04-arm
          - name: amd64
            runner: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Download SQLite amalgamation
        uses: actions/download-artifact@v4
        with:
          name: sqlite-amalgamation
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install cibuildwheel
        run: |
          pip install cibuildwheel[uv]==${{ env.CIBW_VERSION }}

      - name: Build wheels
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch.name == 'aarch64' && 'aarch64' || 'auto' }}
        run: |
          python -m cibuildwheel --output-dir dist

      - name: Upload Linux wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-${{ matrix.arch.name }}-cp311
          path: dist/*.whl

  build_wheels_windows:
    name: Build Windows wheels
    runs-on: windows-latest
    needs: build_sqlite_amalgamation

    steps:
      - uses: actions/checkout@v4

      - name: Download SQLite amalgamation
        uses: actions/download-artifact@v4
        with:
          name: sqlite-amalgamation
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install cibuildwheel
        run: |
          pip install cibuildwheel[uv]==${{ env.CIBW_VERSION }}

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir dist

      - name: Upload Windows wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-windows-cp311
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: build_sqlite_amalgamation

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      - name: Download SQLite amalgamation
        uses: actions/download-artifact@v4
        with:
          name: sqlite-amalgamation
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build sdist
        run: |
          python -m build -s

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: pypi-sdist
          path: dist/*.tar.gz

  collect_artifacts:
    name: Collect all wheels and sdist
    needs: [build_wheels_macos, build_wheels_linux, build_wheels_windows, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
          pattern: '*'
          merge-multiple: false

      - name: Prepare distribution directory
        run: |
          mkdir -p dist
          find all-artifacts -name "*.whl" -exec cp {} dist/ \;
          find all-artifacts -name "*.tar.gz" -exec cp {} dist/ \;
          ls -la dist/

      - name: Upload combined distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/*

  publish-to-pypi:
    name: Publish Python to Pypi
    needs: [collect_artifacts]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    environment:
      name: publish
      url: https://pypi.org/project/rotki-sqlite/

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1